name = "CurveFitModels"
uuid = "1f9b919b-fd1b-4396-9cba-39be8ca4ba18"
version = "0.4.0"
authors = ["Garrek Stemo <8449000+garrekds@users.noreply.github.com>"]

[deps]
CurveFit = "5a033b19-8c74-5913-a970-47c3779ef25c"

[compat]
CurveFit = "1"
