name = "CurveFitModels"
uuid = "a3c2e87f-4d91-4e5b-9f3a-7c8b6d2e1f0a"
version = "0.4.0"
authors = ["Garrek Stemo <8449000+garrekds@users.noreply.github.com>"]

[deps]
CurveFit = "5a033b19-8c74-5913-a970-47c3779ef25c"

[compat]
CurveFit = "1"
