name = "CurveFitModels"
uuid = "a3c2e87f-4d91-4e5b-9f3a-7c8b6d2e1f0a"
version = "0.6.0"
authors = ["Garrek Stemo <8449000+garrekstemo@users.noreply.github.com>"]

[deps]

[extras]
CurveFit = "5a033b19-8c74-5913-a970-47c3779ef25c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CurveFit", "Random", "Test"]
